DATASET:
  root_dataset: "./data/"
  list_train: "../../semantic-segmentation-pytorch/data/alpaca_training.odgt"
  list_val: "../../semantic-segmentation-pytorch/data/alpaca_validation.odgt"
  num_class: 2
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "upernet"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 500
  start_epoch: 251
  epoch_iters: 360
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True
  checkpoint: "epoch_251.pth"

TEST:
  checkpoint: "epoch_251.pth"
  result: "./"

DIR: "../9999_outputs/1_segmentations_ckpts/ade20k-resnet50-upernet_Alpaca"
SAVE_DIR: "../9999_outputs/2_segmentation_output/ade20k-resnet50-upernet_Alpaca_training"
